# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20161021_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('DEFAULT', ''), ('NEWUSER', 'user registered on woozup'), ('NEWPARTICIPANT', 'user joined an event'), ('NEWEVENT', 'user created an event'), ('EVENTCANCELED', 'user canceled an event'), ('NEWFRIEND', 'user connected with another user')], default='DEFAULT', max_length=20),
        ),
    ]
