# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20161021_0729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-updated_at']},
        ),
    ]
