# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 17:03
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('special', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('closed', models.BooleanField(default=False, help_text='if closed no more participants accepted')),
                ('p_limit', models.IntegerField(blank=True, help_text='maximum number of participants', null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('location_address', models.CharField(blank=True, max_length=255)),
                ('location_id', models.CharField(blank=True, max_length=255)),
                ('location_coords', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Type: Geometry, Entry format: GeoJson \n(example: "{ \'type\':\'Point\', \'coordinates\':[125.6, 10.1] }")<br>', null=True, srid=4326)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'event_image')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='\nautofield, not modifiable')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='\nautofield, not modifiable')),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=b'category_image')),
                ('style', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='\nautofield, not modifiable')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='\nautofield, not modifiable')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('style', models.CharField(blank=True, max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=b'type_icon')),
                ('background', models.ImageField(blank=True, null=True, upload_to=b'type_bg')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='\nautofield, not modifiable')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='\nautofield, not modifiable')),
                ('category', models.ManyToManyField(to='event.EventCategory')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventType'),
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_as_owner', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events_as_participant', to='userprofile.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('start', 'event_type', 'owner')]),
        ),
    ]
