# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 10:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_coords',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Type: Geometry, Entry format: GeoJson\n(example: "{ \'type\':\'Point\', \'coordinates\':[125.6, 10.1] }")<br>', null=True, srid=4326),
        ),
    ]
