# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([]),
        ),
    ]
