# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20161014_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invitees',
            field=models.ManyToManyField(blank=True, related_name='events_as_invitee', to='userprofile.ExtendedUser'),
        ),
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_as_owner', to='userprofile.ExtendedUser'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events_as_participant', to='userprofile.ExtendedUser'),
        ),
    ]
