# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('event', '0002_auto_20160215_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invitees',
            field=models.ManyToManyField(blank=True, related_name='events_as_invitee', to='userprofile.UserProfile'),
        ),
    ]
