# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_auto_20170111_1328'),
        ('event', '0005_auto_20161230_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='events_as_invitee', to='link.Contact'),
        ),
    ]
