# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='link.Contact'),
        ),
    ]
