# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 17:03
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='\nType: Geometry, Entry format: GeoJson (example: "{ \'type\' : \'Point\',\n\'coordinates\' : [125.6, 10.1] }")<br>', null=True, srid=4326)),
                ('home', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='\nType: Geometry, Entry format: GeoJson (example: "{ \'type\' : \'Point\',\n\'coordinates\' : [125.6, 10.1] }")<br>', null=True, srid=4326)),
                ('office', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='\nType: Geometry, Entry format: GeoJson (example: "{ \'type\' : \'Point\',\n\'coordinates\' : [125.6, 10.1] }")<br>', null=True, srid=4326)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='\nautofield, not modifiable')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(blank=True, choices=[(b'MA', b'male'), (b'FE', b'female')], max_length=2)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('locale', models.CharField(blank=True, max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'profile_picture')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='\nautofield, not modifiable')),
            ],
        ),
    ]
