# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 14:01
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('validation_code', models.IntegerField(null=True)),
                ('validated', models.BooleanField(default=False)),
                ('code_sent_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='\nType: Geometry, Entry format: GeoJson (example: "{ \'type\' : \'Point\',\n\'coordinates\' : [125.6, 10.1] }")<br>', null=True, srid=4326)),
                ('home', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='\nType: Geometry, Entry format: GeoJson (example: "{ \'type\' : \'Point\',\n\'coordinates\' : [125.6, 10.1] }")<br>', null=True, srid=4326)),
                ('office', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='\nType: Geometry, Entry format: GeoJson (example: "{ \'type\' : \'Point\',\n\'coordinates\' : [125.6, 10.1] }")<br>', null=True, srid=4326)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='\nautofield, not modifiable')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(blank=True, choices=[(b'MA', b'male'), (b'FE', b'female')], max_length=2)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('locale', models.CharField(blank=True, max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'profile_picture')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='\nautofield, not modifiable')),
            ],
        ),
        migrations.AddField(
            model_name='number',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
