# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='code_sent_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='number',
            name='validation_code',
            field=models.IntegerField(null=True),
        ),
    ]
