# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 13:34
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20161009_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True),
        ),
    ]
