# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_extendeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.ExtendedUser'),
        ),
        migrations.AlterField(
            model_name='position',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userprofile.ExtendedUser'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userprofile.ExtendedUser'),
        ),
    ]
