# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text=b'name to be displayed in the app', max_length=255)),
                ('numbers', models.CharField(blank=True, help_text='phone numbers list', max_length=255)),
                ('emails', models.CharField(blank=True, help_text='email addresses list', max_length=255)),
                ('photo', models.CharField(blank=True, help_text=b'local path in the device to a picture', max_length=255)),
                ('status', models.CharField(choices=[(b'NEW', b'new'), (b'PEN', b'pending'), (b'ACC', b'accepted'), (b'IGN', b'ignored'), (b'CLO', b'closed')], default=b'NEW', max_length=3)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='\nautofield, not modifiable')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='\nautofield, not modifiable')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_status', models.CharField(choices=[(b'NEW', b'new'), (b'PEN', b'pending'), (b'ACC', b'accepted'), (b'REJ', b'rejected'), (b'IGN', b'ignored'), (b'BLO', b'blocked')], default=b'NEW', max_length=3)),
                ('receiver_status', models.CharField(choices=[(b'NEW', b'new'), (b'PEN', b'pending'), (b'ACC', b'accepted'), (b'REJ', b'rejected'), (b'IGN', b'ignored'), (b'BLO', b'blocked')], default=b'NEW', max_length=3)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='\nautofield, not modifiable')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='\nautofield, not modifiable')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_as_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_as_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set([('sender', 'receiver')]),
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together=set([('sender', 'numbers', 'emails')]),
        ),
    ]
