# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text=b'name to be displayed in the app', max_length=255)),
                ('numbers', models.CharField(blank=True, help_text='phone numbers list', max_length=255)),
                ('emails', models.CharField(blank=True, help_text='email addresses list', max_length=255)),
                ('photo', models.CharField(blank=True, help_text=b'local path in the device to a picture', max_length=255)),
                ('status', models.CharField(choices=[(b'NEW', b'new'), (b'PEN', b'pending'), (b'ACC', b'accepted'), (b'IGN', b'ignored'), (b'CLO', b'closed')], default=b'NEW', max_length=3)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='\nautofield, not modifiable')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='\nautofield, not modifiable')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_status', models.CharField(choices=[(b'NEW', b'new'), (b'PEN', b'pending'), (b'ACC', b'accepted'), (b'REJ', b'rejected'), (b'IGN', b'ignored'), (b'BLO', b'blocked')], default=b'NEW', max_length=3)),
                ('receiver_status', models.CharField(choices=[(b'NEW', b'new'), (b'PEN', b'pending'), (b'ACC', b'accepted'), (b'REJ', b'rejected'), (b'IGN', b'ignored'), (b'BLO', b'blocked')], default=b'NEW', max_length=3)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='\nautofield, not modifiable')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='\nautofield, not modifiable')),
            ],
        ),
    ]
