# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('link', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_as_receiver', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='link',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_as_sender', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='invite',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set([('sender', 'receiver')]),
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together=set([('sender', 'numbers', 'emails')]),
        ),
    ]
