# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invite',
            new_name='Contact',
        ),
    ]
