# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_auto_20161014_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.ExtendedUser'),
        ),
        migrations.AlterField(
            model_name='link',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_as_receiver', to='userprofile.ExtendedUser'),
        ),
        migrations.AlterField(
            model_name='link',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_as_sender', to='userprofile.ExtendedUser'),
        ),
    ]
